sudo: false

language:
  - cpp

env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
addons:
  apt:
    packages:
      - g++-5
    sources:      
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8

before_install:
  - pip install --user cpp-coveralls

script:
  - cmake -H. -Bbuild
  - cd build
  - cmake --build .
  - ctest

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
