sudo: required

language:
  - cpp
compiler: gcc
dist: trusty

env: CXX=g++-5 CC=gcc-5
addons:
  apt:
    packages:
      - gcc-5
      - g++-5
    sources:      
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8

before_install:
  - pip install --user cpp-coveralls

script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - cmake -H. -Bbuild
  - cd build
  - cmake --build .
  - ctest

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
